### ISSUE TITLE
Mthree error mitigation Wouldnt work for Dynamic Circuits

### ISSUE THREAD

**Issue by hykavitha** [Qiskit-Partners/mthree#131] opened 2022-10-14 06:55 UTC
Here in the circuit below, we are doing mid-circuit measurements & resetting the qubit for some more usage. Apply mthree breaks the code. 

what you are doing with the measurement results ? we are using that for phase correction in the next iteration. 

![image](https://user-images.githubusercontent.com/13769864/195781783-8843b73d-de2b-4d27-8678-2fe95b9fec60.png)

**Comment by nonhermitian** [comment] 2022-10-14 10:07
So in principle M3 works, but the automated tools for finding the `final_measurements` does not yet support it.  That is basically what #127 is about.

What you can do in the mean time is just pass a list of repeated qubit indices into the `apply_correction` method.

E.g.

For this circuit

![image](https://user-images.githubusercontent.com/1249193/195821033-eacc622c-210e-4d22-badb-f3cde12dad8a.png)

one would then calibrate the measured qubits, here just physical qubit 1, and then use that index repeatedly in the correction:

```python

mit = mthree.M3Mitigation(backend)
mit.cals_from_system([1])

mit.apply_correction(raw_counts, [1,1])
```

**Comment by nonhermitian** [comment] 2022-10-14 10:08
Closing this as it is not a bug, and making the automated tools handle these situations is the goal of #127

**Closed by nonhermitian** 2022-10-14 10:08 UTC
